#This is the configuration file for MoS2 computations
#the format is key=value
#matches: key=value
# my-key = value
# my.key= value with spaces
#KEY_NAME =   value123
# complex-key.name = some value here
#does not match:
# = value              # No key
# key =                # No value, this must be filled
# key value            # No equals sign
# my key = value       # Space in key (not allowed)
# key==value          # Multiple equals (first = becomes part of key)

#name of the system
name=MoS2

#dimension of system
dim=2

#directions to study, available directions x,y,z
directions_to_study=x,y

#whether spin is considered
spin=True

truncation_radius=12

lattice_basis=3.5186, 0.0, 0.0; 0.0, 6.3023, 0.0; 0.0, 0.0, 15.0058


space_group=None

space_group_origin=0,0,0

space_group_name_H_M=None

cell_setting=None

# --- Magnetic Space Group Metadata ---
space_group_magn_number_BNS=11.51
space_group_magn_name_UNI=P2_1/m.1
space_group_magn_name_BNS=P2_1/m1
space_group_magn_number_OG=11.2.60
space_group_magn_name_OG=P2_1/m1
point_group_number_Litvin=5.2.13
point_group_name_UNI=2/m.1

Wyckoff_position_num=3


#Wyckoff position label Mo0, input orbitals
Mo0_orbitals=4dx2-y2
#one position of Mo0, coefficients  (fractional coordinates)
Mo0_position_coefs=0.25, 0.17813, 0.50484

#Wyckoff position label S0, input orbitals
S0_orbitals=3px
#one position of S0, coefficients  (fractional coordinates)
S0_position_coefs=0.25, 0.57201, 0.57309

#Wyckoff position label S1, input orbitals
#S1_orbitals=
#one position of S1, coefficients  (fractional coordinates)
#S1_position_coefs=0.25, -0.0818, 0.39649
