#This is the configuration file for RbV2Te2O computations
#the format is key=value
#matches: key=value
# my-key = value
# my.key= value with spaces
#KEY_NAME =   value123
# complex-key.name = some value here
#does not match:
# = value              # No key
# key =                # No value, this must be filled
# key value            # No equals sign
# my key = value       # Space in key (not allowed)
# key==value          # Multiple equals (first = becomes part of key)

#name of the system
name=RbV2Te2O

#dimension of system
dim=2

#directions to study, available directions x,y,z
directions_to_study=x,y

#whether spin is considered
spin=True

truncation_radius=8.2

lattice_basis=4.0525, 0.0, 0.0; 0.0, 4.0525, 0.0; 0.0, 0.0, 8.4336


space_group=123

space_group_origin=0,0,0

space_group_name_H_M=P4/MMM

cell_setting=tetragonal

# --- Magnetic Space Group Metadata ---
space_group_magn_number_BNS=None
space_group_magn_name_UNI=None
space_group_magn_name_BNS=None
space_group_magn_number_OG=None
space_group_magn_name_OG=None
point_group_number_Litvin=None
point_group_name_UNI=None

Wyckoff_position_num=4


#Wyckoff position label O0, input orbitals
#O0_orbitals=
#one position of O0, coefficients  (fractional coordinates)
#O0_position_coefs=0.0, 0.0, 0.0

#Wyckoff position label V0, input orbitals
V0_orbitals=3dxz,3dxy
#one position of V0, coefficients  (fractional coordinates)
V0_position_coefs=0.5, 0.0, 0.0

#Wyckoff position label Te0, input orbitals
#Te0_orbitals=
#one position of Te0, coefficients  (fractional coordinates)
#Te0_position_coefs=0.5, 0.5, 0.15

#Wyckoff position label Rb0, input orbitals
#Rb0_orbitals=
#one position of Rb0, coefficients  (fractional coordinates)
#Rb0_position_coefs=0.0, 0.0, 0.5
